name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Deploy with Capistrano
        env:
          RAILS_ENV: production
        run: |
          bundle exec cap production deploy